name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout del repository
      - uses: actions/checkout@v3

      # 2️⃣ Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # 3️⃣ Installa le dipendenze Flutter
      - run: flutter pub get

      # 4️⃣ Aggiorna i pod (iOS)
      - run: |
          cd ios
          pod install
        shell: bash

      # 5️⃣ Build iOS release senza code signing
      - run: flutter build ios --release --no-codesign

      # 6️⃣ Prepara cartella Payload per IPA
      - run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qr FlutterIpaExport.ipa Payload
        shell: bash

      # 7️⃣ Carica IPA su GitHub Release
      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Release build IPA"
